# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Jobs @ HandsOn.TV
tagline:          Work With Us!
url:              http://jobs.handson.tv
paginate:         3
baseurl:          /
author:
  name:           HandsOn.TV
  url:            http://handson.tv/
  email:          handson@handson.tv

# Custom vars
version:          1.0.0
github:
  repo:           https://bitbucket.org/martinspier/jobs.handson.tv
